# Generated by Django 5.0.2 on 2024-03-02 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubinteraction',
            name='unique_user_to_club',
        ),
        migrations.AddConstraint(
            model_name='clubinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'club_id'), name='unique_user_to_club', violation_error_message='You are already following this club'),
        ),
    ]
