# Generated by Django 5.0.2 on 2024-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_remove_clubinteraction_unique_user_to_club_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clubinteraction',
            table='Club Interaction',
        ),
        migrations.AlterModelTable(
            name='userinteraction',
            table='User Interaction',
        ),
    ]
