# Generated by Django 5.0.2 on 2024-03-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='mentions',
        ),
    ]
