# Generated by Django 5.0.2 on 2024-03-07 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', to_field='slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog_likes', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'Blog likes',
            },
        ),
        migrations.AddConstraint(
            model_name='bloglike',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='unique_user_userblog_like'),
        ),
    ]
