# Generated by Django 5.0.2 on 2024-03-05 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userblog_topics'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubbloglike',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='unique_user_clubblog_like'),
        ),
        migrations.AddConstraint(
            model_name='userbloglike',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='unique_user_userblog_like'),
        ),
    ]
