# Generated by Django 5.0.2 on 2024-03-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_userblog_topics'),
        ('topic', '0002_alter_topic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='user_blogs_topic', to='topic.topic'),
        ),
    ]
