# Generated by Django 5.0.2 on 2024-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userblog_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubblog',
            name='author_type',
            field=models.CharField(default='club', max_length=20),
        ),
        migrations.AddField(
            model_name='userblog',
            name='author_type',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
