# Generated by Django 5.0.2 on 2024-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelTable(
            name='image',
            table='Image',
        ),
    ]
