# Generated by Django 5.0.2 on 2024-02-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='Interest/Topic',
        ),
    ]
