# Generated by Django 5.0.2 on 2024-02-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('club_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
