# Generated by Django 5.0.2 on 2024-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelTable(
            name='club',
            table='Club',
        ),
    ]
